---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: default
  name: vault
spec:
  targetNamespace: vault
  createNamespace: true
  repo: https://helm.releases.hashicorp.com
  chart: vault
  version: 0.28.1
  valuesContent: |
    server:
      logLevel: debug
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: vault.k8s.szp.io
      dataStorage:
        size: 2Gi
    ui:
      enabled: true
