podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false

ingress:
  enabled: true
  ingressClassName: "traefik"
  hostname: sealed-secrets.k8s.szp.io
  annotations:
    cert-manager.io/cluster-issuer: k8s-intermediate
  tls: true
