---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: k8s-gateway
    repoURL: https://ori-edge.github.io/k8s_gateway
    targetRevision: 2.4.0
    helm:
      valuesObject:
        domain: k8s.szp.io
        service:
          labels:
            svccontroller.k3s.cattle.io/lbpool: private
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
