---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.1
    helm:
      valuesObject:
        server:
          logLevel: debug
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: vault.k8s.szp.io
          dataStorage:
            size: 2Gi
        ui:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
