---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadal-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.27
    helm:
      valuesObject:
        primary:
          pgHbaConfiguration: |
            host all all all trust
          persistence:
            size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.zitadel.com
    chart: zitadel
    targetRevision: 8.3.0
    helm:
      valuesObject:
        zitadel:
          # TODO: currently the secret is manually created
          masterkeySecretName: zitadel-masterkey
          configmapConfig:
            ExternalDomain: zitadel.szp15.com
            ExternalSecure: true
            TLS:
              Enabled: false
            Database:
              Postgres:
                Host: zitadal-db-postgresql
                Port: 5432
                Database: zitadel
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  Username: postgres
                  SSL:
                    Mode: disable
                Admin:
                  Username: postgres
                  SSL:
                    Mode: disable
        ingress:
          enabled: true
          className: traefik-public
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            external-dns.alpha.kubernetes.io/target: ingress.szp15.com
          hosts:
            - host: zitadel.szp15.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - zitadel.szp15.com
              secretName: tls-zitadel-ingress-http
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
