site_name: Homelab
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Designs:
      - index.md
      - NixOS Configuration: designs/nixos-config.md
