site_name: Homelab
markdown_extensions:
  - footnotes
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Designs:
      - index.md
      - NixOS Configuration: designs/nixos-config.md
      - Overlay Network: designs/overlay-network.md
      - Dev Cluster (WIP): designs/dev-cluster.md
