[project]
name = "homelab"
version = "0.1.0"
description = "Scripts for my homelab"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.9.2", "pyyaml>=6.0.2", "ruff>=0.7.3"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP"]
