[headscale-ui]
src.github = "gurucomputing/headscale-ui"
fetch.github = "gurucomputing/headscale-ui"
[headscale-ui.passthru]
npmDepsHash = "sha256-vtMRi81GCaZDnfyZG5Eth/kPKQeIAsxhqKcc74ij7lg="

# fetch alpha release
[sing-box]
src.github = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"
[sing-box.passthru]
vendorHash = "sha256-R9dN2/MmuAeYB9UkNDbhc48SelBMR80nMnptNKD0y9c="

[github-actions-cache-server]
src.github = "falcondev-oss/github-actions-cache-server"
fetch.github = "falcondev-oss/github-actions-cache-server"
[github-actions-cache-server.passthru]
pnpmDepsHash = "sha256-SNC9q5p+dTjFm9UaGvdARWD69+1iKgsK12WtdOAjiGU="

[cloudreve]
src.github_tag = "cloudreve/Cloudreve"
fetch.github = "cloudreve/Cloudreve"
git.fetchSubmodules = true
[cloudreve.passthru]
yarnDepsHash = "sha256-9TzmSyKpKqx3eSybfZyWL4LYfUkHVYE+x7shfV54Whc="
vendorHash = "sha256-IcbmPNSCp3tZqXrW4FMAP/aDOF6sr+3bABUaGeq6eHY="
