[headscale-ui]
src.github = "gurucomputing/headscale-ui"
fetch.github = "gurucomputing/headscale-ui"

[terraboard]
src.github = "camptocamp/terraboard"
fetch.github = "camptocamp/terraboard"

# fetch alpha release
[sing-box]
src.github_tag = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"
src.include_regex = "v.*"
[sing-box.passthru]
vendorHash = "sha256-iWhPeoE0MkGMmHEwMmblRaGXNM7RrBq8Vm+/PHSJqKo="

[github-actions-cache-server]
src.github = "falcondev-oss/github-actions-cache-server"
fetch.github = "falcondev-oss/github-actions-cache-server"
[github-actions-cache-server.passthru]
pnpmDepsHash = "sha256-og8VtU+zkC5nKgDSm21qW7GuAVqByUa0JGxc5/MUnPM="
