[headscale-ui]
src.github = "gurucomputing/headscale-ui"
fetch.github = "gurucomputing/headscale-ui"
[headscale-ui.passthru]
npmDepsHash = "sha256-r8MuY7yhjek2SZyJCv5Xhk9dJE2VgKx7RTdOBr0Bji4="

[terraboard]
src.github = "camptocamp/terraboard"
fetch.github = "camptocamp/terraboard"
[terraboard.passthru]
yarnDepsHash = "sha256-KbetB8S8MBJyvzl4Dl87uxRrOLEa6padD5LLHAUz/SI="
vendorHash = "sha256-GarFrn/0x26KTxrUQwXtNYb/rttzT3f94iiWm6/dsHA="

# fetch alpha release
[sing-box]
src.github_tag = "SagerNet/sing-box"
fetch.url = "https://github.com/SagerNet/sing-box/archive/v$ver.tar.gz"
src.include_regex = "v.*"
src.prefix = "v"
[sing-box.passthru]
vendorHash = "sha256-BNRAAfXUFV0CwRXvVu0Ix1yX9ISALsdrfJ0neM+ML9M="

[github-actions-cache-server]
src.github = "falcondev-oss/github-actions-cache-server"
fetch.github = "falcondev-oss/github-actions-cache-server"
[github-actions-cache-server.passthru]
pnpmDepsHash = "sha256-wDGFau1ZdgsjEbaDPBgTwDMYLvkXbyO7VCnZYf4xdsc="

[cloudreve]
src.github_tag = "cloudreve/Cloudreve"
fetch.github = "cloudreve/Cloudreve"
git.fetchSubmodules = true
[cloudreve.passthru]
yarnDepsHash = "sha256-HxXG72TzyzMY/swpydkfPD/h5NHO5ty5NdtDXV9WrFY="
vendorHash = "sha256-InbI0Tx6tRn8lN+UlC/yM305aLdf9/3xALhNChExlhQ="
