[headscale-ui]
src.github = "gurucomputing/headscale-ui"
fetch.github = "gurucomputing/headscale-ui"
[headscale-ui.passthru]
npmDepsHash = "sha256-r8MuY7yhjek2SZyJCv5Xhk9dJE2VgKx7RTdOBr0Bji4="

[terraboard]
src.github = "camptocamp/terraboard"
fetch.github = "camptocamp/terraboard"
[terraboard.passthru]
yarnDepsHash = "sha256-KbetB8S8MBJyvzl4Dl87uxRrOLEa6padD5LLHAUz/SI="
vendorHash = "sha256-GarFrn/0x26KTxrUQwXtNYb/rttzT3f94iiWm6/dsHA="

# fetch alpha release
[sing-box]
src.github_tag = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"
src.include_regex = "v.*"
[sing-box.passthru]
vendorHash = "sha256-t76QBdgTprVM5g6ytl0nG+daO6WEnI1Q5gA3bPMRR9Y="

[github-actions-cache-server]
src.github = "falcondev-oss/github-actions-cache-server"
fetch.github = "falcondev-oss/github-actions-cache-server"
[github-actions-cache-server.passthru]
pnpmDepsHash = "sha256-wDGFau1ZdgsjEbaDPBgTwDMYLvkXbyO7VCnZYf4xdsc="

[cloudreve]
src.github_tag = "cloudreve/Cloudreve"
fetch.github = "cloudreve/Cloudreve"
git.fetchSubmodules = true
[cloudreve.passthru]
# yarnDepsHash = "sha256-5ZZyuFCQMRRfr2sEg1Vm2llHvrQexXyKJZWTOJ54x8c="
yarnDepsHash = "sha256-zVGH8SiL6416yZdDg34AoxsuSmktJA82lzPlvt6E53M="
# vendorHash = "sha256-wEgT+9oL5w0LKpOGYTPo0rzUksFZdbEvO+44Oqt7jGg="
vendorHash = "sha256-InbI0Tx6tRn8lN+UlC/yM305aLdf9/3xALhNChExlhQ="
