---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cert-manager
  name: vault-issuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: vault-issuer
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["vault-issuer"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cert-manager
  name: vault-issuer
subjects:
  - kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: http://vault.vault:8200
    path: pki_int/sign/k8s-szp-io
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: vault-issuer
        serviceAccountRef:
          name: vault-issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: me@szp.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: traefik-external
