name: "Run terragrunt apply"
description: "Run terragrunt apply"

inputs:
  working-directory:
    description: "The working directory"
    default: "terraform"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: tfplans
        path: .data
    - name: Unpack tfplans
      shell: bash
      run: sops -d .data/tfplans.tar.gz.enc | tar -xz -C .data
    - name: Run Terragrunt Apply
      shell: bash
      run: terragrunt run-all apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      env:
        TG_OUT_DIR: ${{ github.workspace }}/.data/tfplans
