k8sServiceHost: "localhost"
k8sServicePort: "6443"
kubeProxyReplacement: true
socketLB:
  hostNamespaceOnly: true
localRedirectPolicy: true
hubble:
  enabled: true
  relay:
    enabled: true
  prometheus:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      hosts:
        - hubble.k8s.szp.io
ipam:
  mode: kubernetes
envoy:
  enabled: false
operator:
  setNodeTaints: false
