# prometheusOperator:
#   networkPolicy:
#     enabled: true
prometheus:
  annotations:
  networkPolicy:
    enabled: true
    ingress:
      - {}
    egress:
      - {}
grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.k8s.szp.io
