prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.k8s.szp.io
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.k8s.szp.io

# kubeProxyReplacement is turned on in cilium
kubeProxy:
  enabled: false
