kubeRBACproxy:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
