cephClusterSpec:
  dashboard:
    ssl: false
  mgr:
    count: 1
  storage:
    useAllNodes: false
    nodes:
      - name: hasee01
        devices:
          - name: /dev/disk/by-id/nvme-JZ-SSD2T-XW_30170722158
      - name: hasee02
        devices:
          - name: /dev/disk/by-id/nvme-JZ-SSD2T-XW_30166624750
      - name: hasee03
        devices:
          - name: /dev/disk/by-id/nvme-JZ-SSD2T-XW_30166624758

ingress:
  dashboard:
    enabled: true
    ingressClassName: traefik
    host:
      name: ceph.k8s.szp.io
      path: /

toolbox:
  enabled: true
