# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  headscale = {
    pname = "headscale";
    version = "v0.23.0-beta1";
    src = fetchFromGitHub {
      owner = "juanfont";
      repo = "headscale";
      rev = "v0.23.0-beta1";
      fetchSubmodules = false;
      sha256 = "sha256-uOaVK+3/DoUDbccelGYRx9zwAG6wYLywYbNN+7epnk0=";
    };
  };
}
