# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cloudreve = {
    pname = "cloudreve";
    version = "4.0.0-beta.13";
    src = fetchFromGitHub {
      owner = "cloudreve";
      repo = "Cloudreve";
      rev = "4.0.0-beta.13";
      fetchSubmodules = true;
      sha256 = "sha256-lsio1disuBK6A53OwBuammGo3+5Tbh3C1Pp8M9EMzwU=";
    };
    vendorHash = "sha256-wEgT+9oL5w0LKpOGYTPo0rzUksFZdbEvO+44Oqt7jGg=";
    yarnDepsHash = "sha256-5ZZyuFCQMRRfr2sEg1Vm2llHvrQexXyKJZWTOJ54x8c=";
  };
  github-actions-cache-server = {
    pname = "github-actions-cache-server";
    version = "v8.0.1";
    src = fetchFromGitHub {
      owner = "falcondev-oss";
      repo = "github-actions-cache-server";
      rev = "v8.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-KD0UE94PrYb8RlxWXVkPmo6E+AgCUapFrhWFaKrA0/I=";
    };
    pnpmDepsHash = "sha256-og8VtU+zkC5nKgDSm21qW7GuAVqByUa0JGxc5/MUnPM=";
  };
  headscale-ui = {
    pname = "headscale-ui";
    version = "2025.05.22";
    src = fetchFromGitHub {
      owner = "gurucomputing";
      repo = "headscale-ui";
      rev = "2025.05.22";
      fetchSubmodules = false;
      sha256 = "sha256-/wDk/ENZSgffDEEat13Yob+NmVuJF4bOPeE0XhwgC9Y=";
    };
    npmDepsHash = "sha256-r8MuY7yhjek2SZyJCv5Xhk9dJE2VgKx7RTdOBr0Bji4=";
  };
  sing-box = {
    pname = "sing-box";
    version = "v1.12.0-beta.19";
    src = fetchFromGitHub {
      owner = "SagerNet";
      repo = "sing-box";
      rev = "v1.12.0-beta.19";
      fetchSubmodules = false;
      sha256 = "sha256-Il3vjTLDR7F7hn1ZLvHoS2EWKy6AOZ5Nt5oQ+1PI6HQ=";
    };
    vendorHash = "sha256-c5/gZVwBeCpNkGRJMf0HjkQ0ttwWfDfNlb0PfuMVlwY=";
  };
  terraboard = {
    pname = "terraboard";
    version = "v2.4.0";
    src = fetchFromGitHub {
      owner = "camptocamp";
      repo = "terraboard";
      rev = "v2.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BkvGOE1ElETp4NLgMC9s8BtzNkskkvFt6/nVgmJNRww=";
    };
    vendorHash = "sha256-GarFrn/0x26KTxrUQwXtNYb/rttzT3f94iiWm6/dsHA=";
    yarnDepsHash = "sha256-KbetB8S8MBJyvzl4Dl87uxRrOLEa6padD5LLHAUz/SI=";
  };
}
