# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cloudreve = {
    pname = "cloudreve";
    version = "4.10.1";
    src = fetchFromGitHub {
      owner = "cloudreve";
      repo = "Cloudreve";
      rev = "4.10.1";
      fetchSubmodules = true;
      sha256 = "sha256-PngA/5WiN7rr7B9Ks4OOWH+27pLCPgAGbxiGF9RiEhg=";
    };
    vendorHash = "sha256-IcbmPNSCp3tZqXrW4FMAP/aDOF6sr+3bABUaGeq6eHY=";
    yarnDepsHash = "sha256-9TzmSyKpKqx3eSybfZyWL4LYfUkHVYE+x7shfV54Whc=";
  };
  github-actions-cache-server = {
    pname = "github-actions-cache-server";
    version = "v8.1.4";
    src = fetchFromGitHub {
      owner = "falcondev-oss";
      repo = "github-actions-cache-server";
      rev = "v8.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-C5X3Fc9MCFO7nbCG3nGmm8cWTKd60lCdh3n43fTOTKw=";
    };
    pnpmDepsHash = "sha256-SNC9q5p+dTjFm9UaGvdARWD69+1iKgsK12WtdOAjiGU=";
  };
  headscale-ui = {
    pname = "headscale-ui";
    version = "2025.08.23";
    src = fetchFromGitHub {
      owner = "gurucomputing";
      repo = "headscale-ui";
      rev = "2025.08.23";
      fetchSubmodules = false;
      sha256 = "sha256-w7Ku4dpkQsm7Mc3yRaTf1MBThnjB3e7V1YeOfMIbyvw=";
    };
    npmDepsHash = "sha256-vtMRi81GCaZDnfyZG5Eth/kPKQeIAsxhqKcc74ij7lg=";
  };
  sing-box = {
    pname = "sing-box";
    version = "v1.12.12";
    src = fetchFromGitHub {
      owner = "SagerNet";
      repo = "sing-box";
      rev = "v1.12.12";
      fetchSubmodules = false;
      sha256 = "sha256-4TQLaDjZYcm8FVBo06c4rKuXEO2xRGm6cIzpkPwtL/g=";
    };
    vendorHash = "sha256-R9dN2/MmuAeYB9UkNDbhc48SelBMR80nMnptNKD0y9c=";
  };
  zteonu = {
    pname = "zteonu";
    version = "v0.0.7";
    src = fetchFromGitHub {
      owner = "Septrum101";
      repo = "zteOnu";
      rev = "v0.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-irw7q64MO9xdL0RXWnWN3ULkHqCGBWuYlsMl7avgfQI=";
    };
    vendorHash = "sha256-tecWPrGGCFmWGjeMA7ct3Vvm85A41dskjx2ntv5cIl8=";
  };
}
