global:
  storageClass: rook-ceph-block

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]

valkey-cluster:
  enabled: false
valkey:
  enabled: true

postgresql-ha:
  enabled: false
postgresql:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: git.k8s.szp.io

service:
  ssh:
    type: LoadBalancer
    annotations:
      metallb.io/allow-shared-ip: "ingress"
