apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    kubeProxyReplacement: true
    localRedirectPolicy: true
